# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginreg', '0005_auto_20160820_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_by', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_creator', to='loginreg.User')),
                ('quote_joiner_id', models.ManyToManyField(related_name='quote_joiner', to='loginreg.User')),
            ],
            managers=[
                ('quoteManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
